# Generated by Django 5.2 on 2025-04-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='data',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='template',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='experience',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='selected_template',
            field=models.CharField(default='template1', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills',
            field=models.TextField(help_text='Comma-separated skills'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
