# Generated by Django 5.2 on 2025-05-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_remove_portfolio_data_remove_portfolio_template_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
