# Generated by Django 5.2 on 2025-05-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
